apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-ing
spec:
  rules:
  - host: staging-ocr.example.com
    http:
      paths:
        - path: /extract
          pathType: Prefix
          backend:
            service:
              name: ocr
              port:
                number: 80
