apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ocr-server
        env:
        - name: MODEL
          value: /production/model
        resources:
          requests:
            cpu: 1
            memory: 150Mi 
          limits:
            cpu: 2
            memory: 200Mi
