apiVersion: v1
kind: Service
metadata:
  name: intro-app-svc
  labels:
    me: wojtek
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: intro-app
    break: the-connection-with-pods
  type: LoadBalancer
