apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ocr
  labels:
    app: ocr
    tier: backend
spec:
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        name: ocr
        app: ocr
        tier: backend
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: ocr-server
        image: "ocr/ocr-server:${VERSION}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ${CPU_REQUESTS}
            memory: ${MEM_REQUESTS}
          limits:
            cpu: 4
            memory: 4096Mi
        ports:
        - containerPort: 1984
        